FROM opstree/ansible

COPY cserver.pub /root/.ssh/id_rsa.pub
COPY cserver /root/.ssh/id_rsa

RUN apt-get update && apt-get -y install python-mysqldb
RUN chmod 600 /root/.ssh/id_rsa

RUN git clone https://github.com/opstree-ansible/osm_zabbix.git -b Release-1.1 /etc/ansible/roles/osm_zabbix
RUN git clone https://github.com/opstree-ansible/zabbix-agent.git /etc/ansible/roles/zabbix-agent
